export const citydata = [
  {
    citys: [
      { id: 0, cityName: "AbuDhabi" },
      { id: 1, cityName: "Amsterdam" },
      { id: 2, cityName: "Athens" },
      { id: 3, cityName: "Atlanta" },
      { id: 4, cityName: "Auckland" },
      { id: 5, cityName: "Austin" },
      { id: 6, cityName: "Baltimore" },
      { id: 7, cityName: "Barcelona" },
      { id: 8, cityName: "Basel" },
      { id: 9, cityName: "Beijing" },
      { id: 10, cityName: "Berlin" },
      { id: 11, cityName: "Boston" },
      { id: 12, cityName: "Brisbane" },
      { id: 13, cityName: "Brussels" },
      { id: 14, cityName: "Budapest" },
      { id: 15, cityName: "BuenosAires" },
      { id: 16, cityName: "Charlotte" },
      { id: 17, cityName: "Chicago" },
      { id: 18, cityName: "Cincinnati" },
      { id: 19, cityName: "Cleveland" },
      { id: 20, cityName: "Cologne" },
      { id: 21, cityName: "Copenhagen" },
      { id: 22, cityName: "Dallas-FortWorth" },
      { id: 23, cityName: "Denver" },
      { id: 24, cityName: "Detroit" },
      { id: 25, cityName: "Dubai" },
      { id: 26, cityName: "Dublin" },
      { id: 27, cityName: "Düsseldorf" },
      { id: 28, cityName: "Fort Lauderdale" },
      { id: 29, cityName: "Frankfurt" },
      { id: 30, cityName: "Geneva" },
      { id: 31, cityName: "Gothenburg" },
      { id: 32, cityName: "Guangzhou" },
      { id: 33, cityName: "Hamburg" },
      { id: 34, cityName: "Helsinki" },
      { id: 35, cityName: "Hong Kong" },
      { id: 36, cityName: "Houston" },
      { id: 37, cityName: "Istanbul" },
      { id: 38, cityName: "Kansas City" },
      { id: 39, cityName: "Kyoto" },
      { id: 40, cityName: "Las Vegas" },
      { id: 41, cityName: "Lisbon" },
      { id: 42, cityName: "London" },
      { id: 43, cityName: "Los Angeles" },
      { id: 44, cityName: "Lyon" },
      { id: 45, cityName: "Madrid" },
      { id: 46, cityName: "Manchester" },
      { id: 47, cityName: "Melbourne" },
      { id: 48, cityName: "Mexico City" },
      { id: 49, cityName: "Miami" },
      { id: 50, cityName: "Milan" },
      { id: 51, cityName: "Minneapolis-StPaul" },
      { id: 52, cityName: "Montréal" },
      { id: 53, cityName: "Moscow" },
      { id: 54, cityName: "Munich" },
      { id: 55, cityName: "Nagoya" },
      { id: 56, cityName: "Nashville" },
      { id: 57, cityName: "New York" },
      { id: 58, cityName: "Newark" },
      { id: 59, cityName: "Oakland" },
      { id: 60, cityName: "Oporto" },
      { id: 61, cityName: "Orlando" },
      { id: 62, cityName: "Osaka" },
      { id: 63, cityName: "Oslo" },
      { id: 64, cityName: "Paris" },
      { id: 65, cityName: "Perth" },
      { id: 66, cityName: "Philadelphia" },
      { id: 67, cityName: "Phoenix" },
      { id: 68, cityName: "Pittsburgh" },
      { id: 69, cityName: "Portland" },
      { id: 70, cityName: "Prague" },
      { id: 71, cityName: "Québec" },
      { id: 72, cityName: "Riverside" },
      { id: 73, cityName: "Rome" },
      { id: 74, cityName: "Rotterdam" },
      { id: 75, cityName: "Sacramento" },
      { id: 76, cityName: "SanAntonio" },
      { id: 77, cityName: "SanDiego" },
      { id: 78, cityName: "SanFrancisco-SanJose" },
      { id: 79, cityName: "SantaAna-Anaheim" },
      { id: 80, cityName: "Seattle" },
      { id: 81, cityName: "Seoul" },
      { id: 82, cityName: "Shanghai" },
      { id: 83, cityName: "Shenzhen" },
      { id: 84, cityName: "Singapore" },
      { id: 85, cityName: "Stockholm" },
      { id: 86, cityName: "Stuttgart" },
      { id: 87, cityName: "Sydney" },
      { id: 88, cityName: "São Paulo" },
      { id: 89, cityName: "Taipei" },
      { id: 90, cityName: "Tampa" },
      { id: 91, cityName: "Tel Aviv" },
      { id: 92, cityName: "Tokyo" },
      { id: 93, cityName: "Toronto" },
      { id: 94, cityName: "Vancouver" },
      { id: 95, cityName: "Vienna" },
      { id: 96, cityName: "Warsaw" },
      { id: 97, cityName: "WashingtonDC" },
      { id: 98, cityName: "Yokohama" },
      { id: 99, cityName: "Zürich" },
    ],
  },
];
